
// Generated by https://quicktype.io

import { User } from "./user.interface";

export interface LoginResponse {
  success: boolean;
  message: string;
  user:    User;
  token:   string;
  error?:  string;
}



